##########################################################################
##  v      #                  The Coq Proof Assistant                   ##
## <O___,, # CNRS-Ecole Polytechnique-INRIA Futurs-Universite Paris Sud ##
##   \VV/  #                                                            ##
##    //   #   Makefile automagically generated by coq_makefile V8.2    ##
##########################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS:=
COQLIBS:= -R . GC
COQDOCLIBS:=-R . GC

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB:=$(shell $(CAMLBIN)camlp5 -where 2> /dev/null || $(CAMLBIN)camlp4 -where)
CAMLP4:=$(notdir $(CAMLP4LIB))
COQSRC:=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS:=$(OCAMLLIBS) $(COQSRC)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
CAMLC:=$(CAMLBIN)ocamlc -rectypes -c
CAMLOPTC:=$(CAMLBIN)ocamlopt -c
CAMLLINK:=$(CAMLBIN)ocamlc
CAMLOPTLINK:=$(CAMLBIN)ocamlopt
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
PP:=-pp "$(CAMLBIN)$(CAMLP4)o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=./card/card_facts.v\
  ./card/card.v\
  ./liveness/notacc_white_nogrey.v\
  ./liveness/until_zero.v\
  ./liveness/notfree_notacc.v\
  ./liveness/liveness.v\
  ./liveness/notacc_black_nogrey.v\
  ./liveness/notacc_init.v\
  ./liveness/notacc_white_ancestor.v\
  ./liveness/fairstr.v\
  ./gc/parameters.v\
  ./gc/gc.v\
  ./safety/rtgreyorblack.v\
  ./safety/noedgeblacktowhite.v\
  ./safety/accnotfree.v\
  ./safety/sweepnogrey.v\
  ./safety/safety.v\
  ./safety/nogreyaccnblackn.v\
  ./lib_arith/lib_plus.v\
  ./lib_arith/lib_S_pred.v\
  ./lib_arith/lemme_arith.v\
  ./lib_arith/lib_minus.v\
  ./mesure/parameters_card.v\
  ./mesure/white_card.v\
  ./mesure/grey_card.v\
  ./mesure/safe_card.v\
  ./mesure/mesure.v\
  ./mesure/black_card.v\
  ./mesure/unicite_mes.v\
  ./reachable/reachable.v\
  ./lemma_step/lemma_mark.v\
  ./lemma_step/lemma_stop.v\
  ./lemma_step/lemma_add.v\
  ./lemma_step/lemma_alloc.v\
  ./lemma_step/lemma_remove.v\
  ./lemma_step/lemma_end.v\
  ./lemma_step/lemma_step.v\
  ./lemma_step/lemma_free1.v\
  ./lemma_step/lemma_free.v\
  ./lemma_step/lemma_call.v\
  ./logique/LTL.v\
  ./logique/well_founded.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: ./card/card_facts.vo\
  ./card/card.vo\
  ./liveness/notacc_white_nogrey.vo\
  ./liveness/until_zero.vo\
  ./liveness/notfree_notacc.vo\
  ./liveness/liveness.vo\
  ./liveness/notacc_black_nogrey.vo\
  ./liveness/notacc_init.vo\
  ./liveness/notacc_white_ancestor.vo\
  ./liveness/fairstr.vo\
  ./gc/parameters.vo\
  ./gc/gc.vo\
  ./safety/rtgreyorblack.vo\
  ./safety/noedgeblacktowhite.vo\
  ./safety/accnotfree.vo\
  ./safety/sweepnogrey.vo\
  ./safety/safety.vo\
  ./safety/nogreyaccnblackn.vo\
  ./lib_arith/lib_plus.vo\
  ./lib_arith/lib_S_pred.vo\
  ./lib_arith/lemme_arith.vo\
  ./lib_arith/lib_minus.vo\
  ./mesure/parameters_card.vo\
  ./mesure/white_card.vo\
  ./mesure/grey_card.vo\
  ./mesure/safe_card.vo\
  ./mesure/mesure.vo\
  ./mesure/black_card.vo\
  ./mesure/unicite_mes.vo\
  ./reachable/reachable.vo\
  ./lemma_step/lemma_mark.vo\
  ./lemma_step/lemma_stop.vo\
  ./lemma_step/lemma_add.vo\
  ./lemma_step/lemma_alloc.vo\
  ./lemma_step/lemma_remove.vo\
  ./lemma_step/lemma_end.vo\
  ./lemma_step/lemma_step.vo\
  ./lemma_step/lemma_free1.vo\
  ./lemma_step/lemma_free.vo\
  ./lemma_step/lemma_call.vo\
  ./logique/LTL.vo\
  ./logique/well_founded.vo

spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

.SUFFIXES: .v .vo .vi .g .html .tex .g.tex .g.html

%.vo %.glob: %.v
	$(COQC) -dump-glob $*.glob $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob  -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob -html -g $< -o $@

%.v.d.raw: %.v
	$(COQDEP) -slash $(COQLIBS) "$<" > "$@"\
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

%.v.d: %.v.d.raw
	$(HIDE)sed 's/\(.*\)\.vo[[:space:]]*:/\1.vo \1.glob:/' < "$<" > "$@" \
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f $(VOFILES) `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o $(VOFILES) $(VIFILES) $(GFILES) *~
	rm -f all.ps all-gal.ps all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html

archclean:
	rm -f *.cmx *.o


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

